#
# Copyright (c) 2022 Intel Corporation. 
#
# SPDX-License-Identifier: Apache-2.0
#
#
controller:
  config:
    ssl-ecdh-curve: secp384r1:secp521r1
    ssl-protocols: TLSv1.3
  ingressClassResource:
    default: true
  service:
    type: NodePort
    nodePorts:
      http: 32080
      https: 32443
      tcp:
        8080: 32808
{{- range .Kitconfig.Components.Selector -}}
{{- if eq .Name "jitsi-meet" }}
  hostNetwork: true
{{- end -}}
{{- end }}
