
publicURL: "https://www.myjitsi.com"

web:
  ingress:
    enabled: true
    hosts:
    - host: www.myjitsi.com
      paths: ['/']
    tls:
      - secretName: jitsi-web-certificate
        hosts:
          - www.myjitsi.com

jvb:
  publicIP: 192.168.3.197
  UDPPort: 31000
  service:
    enabled: true
    type: NodePort
