
publicURL: "https://www.esclub.space:8087"

web:
  ingress:
    enabled: true
    hosts:
    - host: www.esclub.space
      paths: ['/']
    tls:
      - secretName: jitsi-web-certificate
        hosts:
          - www.esclub.space

jvb:
  publicIP: www.esclub.space
  UDPPort: 31000
  service:
    enabled: true
    type: NodePort
  websockets:
    enabled: true
