
publicURL: "https://www.esclub.space:8087"
enableAuth: true
tz: Asia/Hong_Kong

web:
  ingress:
    enabled: true
    hosts:
    - host: www.esclub.space
      paths: ['/']
    tls:
      - secretName: jitsi-web-certificate
        hosts:
          - www.esclub.space
  image:
    repository: 192.168.3.116:9000/library/neusoft-web
    tag: v1.0.4
          # tag: 'stable-7001'

jvb:
  publicIP: www.esclub.space
  UDPPort: 31000
  service:
    enabled: true
    type: NodePort
  websockets:
    enabled: true
  image:
    tag: 'stable-7001'

jicofo:
  image:
    tag: 'stable-7001'

prosody:
  image:
    tag: 'stable-7001'

